language: java
jdk:
  - openjdk17
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app:  "spring-book-store"
  on:
    branch: main